# Generated by Django 4.2.24 on 2025-10-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='ministryinfo',
            name='lead_steward_image',
            field=models.ImageField(blank=True, null=True, upload_to='ministry/leaders/'),
        ),
    ]
