# Generated by Django 5.2.7 on 2025-10-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_alter_carouselimage_image_and_more'),
    ]

    operations = [
    ]
