# Generated by Django 5.2.7 on 2025-10-06 20:23

import ckeditor.fields
import cloudinary.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_add_created_at_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministryinfo',
            name='about_text',
        ),
        migrations.AddField(
            model_name='ministryinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='carousel_images'),
        ),
        migrations.AlterField(
            model_name='ministryinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ministryinfo',
            name='lead_steward_bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ministryinfo',
            name='lead_steward_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ministry_leaders'),
        ),
    ]
