# Generated by Django 4.2.24 on 2025-10-06 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KES', max_digits=10, verbose_name='amount')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether to keep the donation anonymous', verbose_name='is anonymous')),
                ('payment_reference', models.CharField(blank=True, help_text='Reference number from payment processor', max_length=100, verbose_name='payment reference')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('partnership_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='one_time', max_length=20, verbose_name='partnership type')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount in KES', max_digits=10, null=True, verbose_name='amount')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='status')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this is a recurring payment', verbose_name='is recurring')),
                ('next_payment_date', models.DateField(blank=True, help_text='Next payment date for recurring partnerships', null=True, verbose_name='next payment date')),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of the last successful payment', null=True, verbose_name='last payment date')),
                ('payment_reference', models.CharField(blank=True, help_text='Reference number from payment processor', max_length=100, verbose_name='payment reference')),
            ],
            options={
                'verbose_name': 'Partnership',
                'verbose_name_plural': 'Partnerships',
                'ordering': ['-created_at'],
            },
        ),
    ]
