# Generated by Django 4.2.24 on 2025-10-06 18:07

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', help_text='Whether the event is upcoming or past', max_length=20)),
                ('category', models.CharField(choices=[('light_central', 'Light Central Meeting'), ('photizo_1', 'Photizo 1'), ('photizo_2', 'Photizo 2'), ('special', 'Special Event')], help_text='Type of event', max_length=50)),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('end_date', models.DateTimeField(blank=True, help_text="End date and time if it's a multi-day event", null=True)),
                ('location', models.TextField(help_text='Event venue or location details')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='event_images')),
                ('youtube_link', models.URLField(blank=True, help_text='Link to event recording or promo video')),
                ('featured', models.BooleanField(default=False, help_text='Featured events appear in special sections')),
                ('registration_required', models.BooleanField(default=False, help_text='Whether registration is required for this event')),
                ('registration_link', models.URLField(blank=True, help_text='Link to registration page if registration is required')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map location', max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
