# Generated by Django 5.2.7 on 2025-10-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcategory_remove_event_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
    ]
