# Generated by Django 5.2.7 on 2025-10-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_registration_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upcoming',
            field=models.BooleanField(default=True, help_text='Automatically set based on event_date'),
        ),
    ]
