# Generated by Django 4.2.25 on 2025-10-07 15:38

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sermon_thumbnails')),
                ('order', models.IntegerField(default=0, help_text='Order in which the playlist appears in listings')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SermonCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, help_text='Thumbnail image for the category', max_length=255, null=True, verbose_name='category_thumbnails')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the category appears in listings')),
            ],
            options={
                'verbose_name': 'Sermon Category',
                'verbose_name_plural': 'Sermon Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('preacher', models.CharField(max_length=100)),
                ('sermon_date', models.DateField(help_text='Date the sermon was delivered')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, help_text='Upload the audio file', max_length=255, null=True, verbose_name='sermon_audio')),
                ('soundcloud_embed', models.URLField(blank=True, help_text='SoundCloud embed URL if hosted externally')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, help_text='Custom thumbnail image for the sermon', max_length=255, null=True, verbose_name='sermon_thumbnails')),
                ('bible_references', models.TextField(blank=True, help_text='Bible references (e.g., John 3:16-17, Romans 8:28-30)')),
                ('description', models.TextField(blank=True, help_text='Detailed description or notes about the sermon')),
                ('play_count', models.IntegerField(default=0, help_text='Number of times the sermon has been played')),
                ('download_count', models.IntegerField(default=0, help_text='Number of times the sermon has been downloaded')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured sermons appear in prominent sections')),
                ('order', models.IntegerField(default=0, help_text='Order in which the sermon appears in listings')),
                ('is_published', models.BooleanField(default=True, help_text='Whether the sermon is published and visible to users')),
                ('category', models.ForeignKey(blank=True, help_text='The category this sermon belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.sermoncategory')),
                ('playlist', models.ForeignKey(blank=True, help_text='The playlist this sermon belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.playlist')),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
                'ordering': ['-sermon_date', 'order'],
            },
        ),
    ]
