# Generated by Django 4.2.24 on 2025-10-06 18:12

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(help_text='Detailed address of the house')),
                ('meeting_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='house_images')),
                ('description', models.TextField(blank=True, help_text='Additional information about the house')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this house is currently active')),
                ('order', models.IntegerField(default=0, help_text='Order in which the house appears in listings')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map location', max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['order', 'name'],
            },
        ),
    ]
