# Generated by Django 5.2.7 on 2025-10-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_meeting_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='house',
            name='longitude',
        ),
    ]
