# Generated by Django 5.2.7 on 2025-10-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_house_latitude_remove_house_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
    ]
