# Generated by Django 4.2.25 on 2025-10-07 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_remove_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image of the house', max_length=255, null=True, verbose_name='image'),
        ),
    ]
