# Generated by Django 4.2.25 on 2025-10-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_house_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
    ]
