# Generated by Django 4.2.25 on 2025-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_remove_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='meeting_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20),
        ),
    ]
